version: "3.9"

services:
  genai-app:
    build: .

    container_name: genai-document-assistant

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data

    env_file:
      - backend/.env

    restart: unless-stopped